### ISSUE TITLE
Null reference after .updateTiles() when using images not used before.

### ISSUE THREAD

**Issue by keithloughnane** [RafaelBarbosatec/bonfire#227]
How to reproduce. I was trying to load a new level.

- Use BonfireWidget(..) to load some tiles, like in the Manual example.
- do gameRef.map.updateTiles(newTiles)

When loading the tiles with updateTiles if the image asset has been used before it will be ok but if the image has not been used before it will crash. Currently I am working around this by loading some 1x1 tiles off screen to pre-load the images.

Thanks very much for your hard work. I am loving the engine so far.

-----------------------------------------------------------------------------------------------

In browser:
Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:53302/dart_sdk.js:5067:11)
    at Object.nullCheck (http://localhost:53302/dart_sdk.js:5394:30)
    at Function.getSprite (http://localhost:53302/packages/bonfire/widgets/bonfire_widget.dart.lib.js:9583:57)
    at tile_model.TileModelSprite.new.getSprite (http://localhost:53302/packages/bonfire/widgets/bonfire_widget.dart.lib.js:10436:50)
    at tile_model.TileModel.new.getTile (http://localhost:53302/packages/bonfire/widgets/bonfire_widget.dart.lib.js:10676:85)
    at MappedListIterable.new.<anonymous> (http://localhost:53302/packages/bonfire/widgets/bonfire_widget.dart.lib.js:6981:62)
    at MappedListIterable.new.elementAt (http://localhost:53302/dart_sdk.js:24312:25)
    at ListIterator.new.moveNext (http://localhost:53302/dart_sdk.js:24101:55)
    at JsIterator.next (http://localhost:53302/dart_sdk.js:6873:21)
    at Function.of (http://localhost:53302/dart_sdk.js:46768:18)
    at MappedListIterable.new.toList (http://localhost:53302/dart_sdk.js:23908:30)
    at map_world.MapWorld.new.[_buildTiles] (http://localhost:53302/packages/bonfire/widgets/bonfire_widget.dart.lib.js:6981:118)
    at map_world.MapWorld.new.[_searchTilesToRender] (http://localhost:53302/packages/bonfire/widgets/bonfire_widget.dart.lib.js:6868:56)
    at Object._microtaskLoop (http://localhost:53302/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:53302/dart_sdk.js:40714:13)
    at http://localhost:53302/dart_sdk.js:36191:9
    
on Android:
E/flutter (16284): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (16284): #0      MapAssetsManager.getSprite (package:bonfire/map/map_assets_manager.dart:27:63)
E/flutter (16284): #1      TileModelSprite.getSprite (package:bonfire/map/tile/tile_model.dart:26:29)
E/flutter (16284): #2      TileModel.getTile (package:bonfire/map/tile/tile_model.dart:173:27)
E/flutter (16284): #3      MapWorld._buildTiles.<anonymous closure> (package:bonfire/map/map_world.dart:222:16)
E/flutter (16284): #4      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
E/flutter (16284): #5      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
E/flutter (16284): #6      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:206:27)
E/flutter (16284): #7      new _GrowableList.of (dart:core-patch/growable_array.dart:153:28)
E/flutter (16284): #8      new List.of (dart:core-patch/array_patch.dart:51:28)
E/flutter (16284): #9      ListIterable.toList (dart:_internal/iterable.dart:213:44)
E/flutter (16284): #10     MapWorld._buildTiles (package:bonfire/map/map_world.dart:223:8)
E/flutter (16284): #11     MapWorld._searchTilesToRender (package:bonfire/map/map_world.dart:83:26)
E/flutter (16284): #12     _rootRun (dart:async/zone.dart:1418:47)
E/flutter (16284): #13     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (16284): #14     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (16284): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (16284): #16     _rootRun (dart:async/zone.dart:1426:13)
E/flutter (16284): #17     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (16284): #18     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (16284): #19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (16284): #20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (16284): #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (16284):

**Comment by RafaelBarbosatec** [comment]
Hi @keithloughnane !
Try use 2.2.5 version! 
If you need anything, I'm at your disposal

**Comment by keithloughnane** [comment]
@RafaelBarbosatec Thanks, have a few beers on me.
