### ISSUE TITLE
Can't get it running

### ISSUE THREAD

**Issue by Zerotask** [RafaelBarbosatec/bonfire#263]
I created a new flutter project in VS Code and then followed the steps from https://bonfire-engine.github.io/#/get-started?id=creating-your-map and https://www.youtube.com/watch?v=hVCmLqZ0JVw

If I start it with windows (x64), a new window opens and closes directly, jumping to here
![image](https://user-images.githubusercontent.com/20150243/174136070-595bbf34-9b09-4103-8e34-ad8cbad3c6fb.png)

I then tried running with the edge browser:
![image](https://user-images.githubusercontent.com/20150243/174136266-cc5e2fa6-0b08-49ca-8c61-778cafe5e334.png)

I'm using the latest versions - installed flutter today. bonfire 2.6.0

In my pubspec.yaml I added:
```yaml
assets:
    - assets/images/
```
Within assets/images is a map.json file, created by Tiled. Nothing fancy.

my lib/main.dart is
```dart
import 'package:bonfire/bonfire.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'World of test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'World of test'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return BonfireTiledWidget(
      joystick: Joystick(directional: JoystickDirectional()),
      map: TiledWorldMap('map.json', forceTileSize: const Size(64, 64)),
    );
  }
}
```

**Comment by Zerotask** [comment]
I just tried it with Android Studio and a refresh project.

Android 12 with Virtual Devices just shows a black screen with a spinner.
Starting with windows device it's the same
```
Building Windows application...
Debug service listening on ws://127.0.0.1:51525/i4MqT9VdBNQ=/ws
Syncing files to device Windows...
flutter: (TiledWorldMap) Error: Null check operator used on a null value

======== Exception caught by widgets library =======================================================
The following StateError was thrown building FutureBuilder<void>(dirty, state: _FutureBuilderState<void>#b78f1):
Bad state: No element

The relevant error-causing widget was: 
  BonfireTiledWidget BonfireTiledWidget:file:///C:/Users/phintermayer/StudioProjects/untitled/lib/main.dart:35:12
When the exception was thrown, this was the stack: 
#0      List.first (dart:core-patch/growable_array.dart:343:5)
#1      MapWorld._createQuadTree (package:bonfire/map/map_world.dart:129:22)
#2      MapWorld.onLoad (package:bonfire/map/map_world.dart:248:5)
<asynchronous suspension>
#3      BonfireGame.onLoad (package:bonfire/base/bonfire_game.dart:161:5)
<asynchronous suspension>
#4      _GameWidgetState.loaderFuture.<anonymous closure> (package:flame/src/game/game_widget/game_widget.dart:186:11)
<asynchronous suspension>
#5      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:627:33)
<asynchronous suspension>
```

**Comment by RafaelBarbosatec** [comment]
Hi @Zerotask !
In `assets/image` there are the map json and tileset json?

By the error displayed. looks like it didn't find the tileset data.

What version of the Tiled you are using?

**Comment by Zerotask** [comment]
My Tiled version is 1.8.6

> In assets/image there are the map json, tileset json and images used in tileset?

map.json and tileset.png. In Tiled I set the embed in map option for the tileset. There is also a tilesets key in the map.json.

I also tested it with a standalone tileset file (called default.tsx) which produces the same error.
![image](https://user-images.githubusercontent.com/20150243/174148417-be8190ca-1d3e-44c8-aecb-b7067fe60e9c.png)

```json
{ "compressionlevel":-1,
 "height":30,
 "infinite":false,
 "layers":[
        {
         "data":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         "height":30,
         "id":1,
         "name":"boden",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":30,
         "x":0,
         "y":0
        }, 
        {
         "data":[11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
            11, 11, 11, 11, 11, 36, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
            11, 11, 11, 11, 36, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
            11, 11, 11, 36, 36, 11, 11, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
            11, 11, 11, 36, 11, 11, 36, 36, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 36, 36, 36, 36, 36, 11, 11, 11, 11, 11, 11,
            11, 11, 36, 36, 11, 36, 36, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 36, 36, 11, 11, 11, 11, 11,
            11, 11, 36, 11, 11, 36, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 36, 36, 11, 11, 11, 11,
            11, 11, 36, 11, 11, 36, 11, 11, 11, 11, 36, 36, 36, 36, 36, 36, 36, 11, 11, 11, 11, 11, 11, 11, 11, 36, 11, 11, 11, 11,
            11, 11, 36, 11, 11, 36, 36, 11, 11, 36, 36, 11, 11, 11, 11, 11, 36, 36, 36, 36, 11, 11, 11, 11, 11, 36, 36, 11, 11, 11,
            11, 11, 36, 11, 11, 11, 36, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 36, 36, 36, 11, 11, 11, 11, 36, 11, 11, 11,
            11, 11, 36, 11, 11, 11, 36, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 36, 36, 11, 11, 11, 36, 11, 11, 11,
            11, 11, 36, 36, 11, 11, 36, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 36, 11, 11, 11, 36, 11, 11, 11,
            11, 11, 11, 36, 11, 11, 36, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 36, 11, 11, 11, 36, 11, 11, 11,
            11, 11, 11, 36, 11, 11, 36, 36, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 36, 11, 11, 11, 36, 11, 11, 11,
            11, 11, 11, 36, 11, 11, 11, 36, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 36, 11, 11, 11, 36, 11, 11, 11,
            11, 11, 11, 36, 11, 11, 11, 36, 36, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 36, 36, 11, 11, 11, 36, 11, 11, 11,
            11, 11, 11, 11, 36, 11, 11, 11, 36, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 36, 11, 11, 11, 11, 36, 11, 11, 11,
            11, 11, 11, 11, 36, 36, 11, 11, 36, 36, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 36, 36, 11, 11, 11, 36, 36, 11, 11, 11,
            11, 11, 11, 11, 11, 36, 11, 11, 11, 36, 36, 36, 11, 11, 11, 11, 11, 11, 11, 36, 36, 11, 11, 11, 11, 36, 11, 11, 11, 11,
            11, 11, 11, 11, 11, 36, 36, 11, 11, 11, 11, 36, 36, 36, 36, 36, 36, 36, 36, 36, 11, 11, 11, 11, 36, 36, 11, 11, 11, 11,
            11, 11, 11, 11, 11, 11, 36, 36, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 36, 11, 11, 11, 11, 11,
            11, 11, 11, 11, 11, 11, 11, 36, 36, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 36, 36, 11, 11, 11, 11, 11,
            11, 11, 11, 11, 11, 11, 11, 11, 11, 36, 36, 36, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 36, 36, 11, 11, 11, 11, 11, 11,
            11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 36, 36, 36, 36, 36, 11, 11, 11, 11, 11, 36, 36, 11, 11, 11, 11, 11, 11, 11,
            11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 36, 36, 36, 36, 36, 36, 36, 11, 11, 11, 11, 11, 11, 11, 11,
            11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
            11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
            11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
            11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
            11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
         "height":30,
         "id":2,
         "name":"ebene2",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":30,
         "x":0,
         "y":0
        }],
 "nextlayerid":3,
 "nextobjectid":1,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.8.6",
 "tileheight":64,
 "tilesets":[
        {
         "firstgid":1,
         "source":"default.tsx"
        }],
 "tilewidth":64,
 "type":"map",
 "version":"1.8",
 "width":30
}
```
